from string import ascii_uppercase
from collections import OrderedDict
from operator import itemgetter

text = """LZKMP KCC MSISYBKXR HQ QPH XOCM VSCSF YQ GKDEWPQ MM JOC GKCEST YY HJO MOPU, LBF
YQ VCFTBI XZHJSYU VY OC. QXNS QB EKKMP GJO SOF ZPSROO WPDZ HJO MCQU SST CTGVOC
KCC CSCNTBI, LFH KD SOF XZ DKMEITOD CT MZBXOCGCDTCPC TB KD, "LBF GSOV SD HJO
FGG YQ O DYZY," VRZIIRE ONSNS, "YSEVQEE DKMEITOD CT MZBXOCGCDTCPC?" DC URP KCC
NCPCTRGBTBI SY VGB ZKP WTBF (KD KGVW OU CSS EYFZF, PZF VRP RCI XOFO SST PPSN
FPFA CWSGZJ OPN DHWZTR), YRPHJOC HJO AZGKDITO ZT OKVWPQ L RCSDM-ERLWP GZINN MS
YYCHJ DSS VBZIDVP CH QPHVSYU WZ LBF ZTQMSYU VRP RCSDWGC, HVGX DIFNPBNI L KJSES
TKMPKD HWVR AWPU PMGC COP MWCUO MM JOC. HJOCS YKD BQDSWPQ DC XOCM TOXOTULPNO
TB VRLH, PYC RKN LZKMP HJSYY KD DC XOCM OENV QEE CH DSS YKJ HQ RPOT DSS TKMPKD
DOA DZ WVCPZH, "YS RGKC! CJ NPOT! S DVCVW PG DZC NKES!" DEE KJOY HJO CODLTH
CMEICVWM VYZY C GLHER ZIV YQ WVC HOKCEQQKE-DQMVSV KYR NYZYGN LH KD LBF DSSP
RFFTSPR QX, LZKMP GVKCHGN EC JOC TGOE, TQB TH HVLGJOO OEBZGU RPF OSYR VRLH URP
VCN YSXOC PGPZFG CPSP K CODLTH YSEV GSEVGB L KCSDHEYLH-RYNYGD, ZF C GLHER EC
VKVS QEE CH SE, OPN, MITXTBI GTHJ MFFKYDWVI, DVG BLB CMCCUC EVG PTSNN LTVOC WV
KYR YKD XWCE WP DTAG DZ GGO TH RYA RQGY O NKCUG BLPDSE-VQVP, IPNPF VRP VGNRS.
KX LBQDSST WZAGXE, RQGY KGXE ONSNS CPEST SE! HJO CODLTH-JYWS YOYH UDCOKQSH QX
WWMO L HWXYSN PZF UYXS YKJ OPN EVGX OWRZPR UEORGXWM FYHB, UY DIFNPBNI EVCD
LZKMP VCN YCV K XCOOYH VY EVKXV ODYFH UDZDRSYU JOCGGVQ PGPZFG CSS HYFBF RPFUOWT
HKWZKXR RQGY KJKE GGOXSF DZ PG K GSTI OSGZ HSNV. PWVRPF VRP KGVW KCC GSTI
OSGZ, ZF URP TGVW JGBJ GNYHZA, PZF URP VCN AZGXEM QP EWOO, LG URP KGXE RQGY,
HQ VZCM KMCWD SST. PTFUD, DVG DCWGN EC OKVS QEE KJKE GJO HOU MZAKXR HQ, LFH
KD HOU DZC FKCY VY DSG KYMVRTBI; DSSP CSS NYZYGN LH VRP GKNPG QP EVG GPZN KYR
PYEWEOO HJKE HJOJ KGBP TKVWSF GTHJ MFDDYLFFC LBF LZCM-CSSNFPG; JOCS CXO HJOCS
URP GCG XORC LBF ZTQVECSU RFBI EACP ZPUU. CSS VYZY FYHB C TLF HBZA QXP CH DSS
URPZXOD OU CSS RKDGGN. TH YKD ZCLPZGN "ZFCXRS OKCACVLRG," LFH, VY SST QCSCD
OWUKADQSYHOOYH, KD HOU OXDVI; DVG NTR PYE ZKUP HQ NCCR DSS LKC, GQ WLBCQPR
VY AIV SE WPDZ CPO ZT VRP QWZMCCBOG CC DVG PPZN ZLGV SE. RQGY, RQGY, RQGY!
KQEWR VRP TCVW BGFPF EYXS VY LB GXO? HJOCS YKD BQDSWPQ PZUO EC FY, DC CVTQG
CZCP LPUCX EONUTBI DZ VGBDSNP. "OWPKS’ZN WTGU WP JGBJ AWMS HQ-XTUJD, T GJYFZF
DSWPU!" (OWPKS KCC EVG MLH.) "K RZDG DSSA’VW FGWPADOC VGB DOWMPF QP XWNU LH
VOL-HKWP. RKXLV, OI OSCB, T KKCS MQE HSTO OCYX SSTO HWVR XS!" CVTQG PPZV DSOV
CSS YKD RQJTBI YQT, YRPB UEORGXWM, VRFAR! DSIOZ! OCYX DVG MLAG EACP K SSCZ
ZT UDTQMC LBF NCM NOLJGC, LBF DSS HKWZ YKD CXOC. ONSNS YKD BQD L PKD SITD,
LBF CSS LEXDGN FD KX L AQWPBV. CSS NYZYGN FD, DEE WV GLG CVW RCBV CXOCVGKO;
PGPZFG RPF YKD OPYEVGB WCPQ AOUCLUG KYR VRP KJSES TKMPKD HOU CEWNV TB USRVV,
RFFTITBI NZKP SE. HJOCS YKD BQD L AQWPBV DZ PG VZGV. KHOA GPBV KWWEO WWMO EVG
GTBF KYR YKD XWCE WP DTAG DZ VGKC WV CLM, CC TH VECBGN L QQBYST, "YS, AA OLFU 
KYR YRTGMOCG, JYH ZCDP WV’C RSVDTBI!" CSS YKD QNYDS DOSWPN TH YRPB URP HWBYSF
DSS EYCBGB, MIV DSS TKMPKD HOU XZ ZQXRST DZ PG CPSP. CSS HYFBF RPFUOWT KX L
ZQXR, ZQG SONV, HVKMS KCC WWV EA PA K CCY YQ ZCWAG JKYUKXR TTYX HJO CCQP. EVGBP
KGBP RQYCG CVW ’FQEYR VRP VCVW, PWD EVGI HSTO LZN VZQMOO; OPN HVGX LZKMP VCN
MSGX LZN DSS YKJ RQGY CPO DWFO LBF EA HJO ZHJOC, HTITBI OGSTI OCQB, DVG GLZMOO
GCNWM FYHB VRP AKNOZG, GZBFOCWPQ SCY CSS YKD SXOC HQ QPH QEE OIKTB. UEORGXWM
URP QCWP IRYY O NSEHNO EODVP, ONV XOFO ZT UYWWF QWOUC. EVGBP KCC YCVRTBI YY
WV LFH C DTBA QZZFOY YGI, LBF KWWEO’D TKBDH KNPO YKD HJKE HJSD AKQSH DOWCPQ
EC QXP CH DSS FYZFU YQ HJO SONV; MIV, KWOU! OTHJOC HJO WCEUD KGBP HQY WOTQP,
CT DSS MOJ KCC ECQ CXONV, MIV, KE OPI COVO, TH YYFZF XZH QZPB CXJ CH DSSO.
RZKGFPF, QX EVG CPQQXO HKWP ’FQEYR, URP QCWP IRYY O NYH QWBEOKX DVG RLR PYE
BQDTQGN MSHYCS, CXO PGRTBF SE KCC L ZKDEZG NZCT KMCWD QWHDPSP SYQJOD VKQS. GJO
EFKOO HJO WWVDWS IYWRGX VSA SY HJO WCEU, LBF DZ VGB RFGKE RGVTUJD, TH HSEHGN!"""


chars = {}
for c in ascii_uppercase:
    chars[c] = 0

for c in text:
    if c.isalpha():
        chars[c] += 1

orderedChars = OrderedDict(reversed(sorted(chars.items(), key=itemgetter(1))))
print(orderedChars)

textWithoutSpace = text.replace(" ", "")
with open('textWithoutSpace.txt', 'w') as file:
    file.write(textWithoutSpace)